name: Deploy to Vercel

on:
  push:
    branches:
      - fe-base-1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2
    - name: Setup Node.js
      uses: actions/setup-node@v4.1.0
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Vercel CLI
      run: npm install --global vercel@latest
    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=production --token=${{ secrets.FE_BASE_1_VERCEL_TOKEN }}
    - name: Build Project Artifacts
      run: vercel build --prod --token=${{ secrets.FE_BASE_1_VERCEL_TOKEN }}
    - name: Deploy Project Artifacts to Vercel
      run: vercel deploy --prebuilt --prod --token=${{ secrets.FE_BASE_1_VERCEL_TOKEN }}