name: Node.js CI

on:
  push:
    branches:
      - fe-base-1
  pull_request:
    branches:
      - fe-base-1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Setup Node.js
      uses: actions/setup-node@v4.1.0
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install
    